### ISSUE TITLE
Did you change your mind about continuing this?

### ISSUE THREAD

**Issue by elgalu** [elviejokike/awssagemaker4jhub#1]

**Comment by elviejokike** [comment]
Hi @elgalu , i do.... just enjoying my vacations....  but, if you want to contribute you are totally welcome.

**Comment by elgalu** [comment]
Well we had a similar idea so first thing I did was googling JupyterHub SageMaker ... and here we are :D

**Comment by georghildebrand** [comment]
i strongly believe this would be an awesome thing to have!!!

**Comment by elviejokike** [comment]
i would, to start, to apply the same design as https://github.com/elviejokike/awsspawner4jhub, but using sagemaker api instead using ess/ec2 API.

**Comment by georghildebrand** [comment]
@elgalu we should add this to our discussion with the architects

**Comment by georghildebrand** [comment]
@elviejokike thanks a lot for your idea! lets see if we can bring this forward

**Comment by elgalu** [comment]
ah this didn't fly after all
